steps:

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.netrc.enc
  - --plaintext-file=.netrc
  - --location=global
  - --keyring=builder
  - --key=builder
  id: kms

- name: 'golang:1.12-stretch'
  entrypoint: 'bash'
  args:
  - '-c'
  - >-
    cp .netrc ~/;
    apt-get update;
    apt-get install -y --no-install-recommends libzmq3-dev;
    go build ./...;
    wget -q -O - https://github.com/golangci/golangci-lint/releases/download/v$$GOLANGCI_VERSION/golangci-lint-$$GOLANGCI_VERSION-linux-amd64.tar.gz |
    tar xzf -;
    golangci-lint-$$GOLANGCI_VERSION-linux-amd64/golangci-lint run ./pkg/...
  env:
  - 'GOLANGCI_VERSION=1.17.1'
